# Generated by Django 5.2.x on 2025-11-01

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(max_length=128, blank=True, null=True),
        ),
    ]
